### ISSUE TITLE
Can't scroll with mouse/pointer in Radix Popover

### ISSUE THREAD

**Issue by phuctm97** [missive/emoji-mart#752]
When being rendered in [Radix UI Popver](https://www.radix-ui.com/docs/primitives/components/popover), the emoji picker scroll area doesn't scroll with mouse/pointer. Scroll with keyboard & manually clicking the scrollbar thumb still works.

I try rendering the emoji picker outside of popover and it works fine.

**Comment by EtienneLem** [comment]
Given EmojiMart uses Shadow DOM, it feels like it would be an issue with Radix. To be sure, can you provide an example (i.e. on https://codesandbox.io) where this issue happens? Thank you.

**Comment by benjaminwaterlot** [comment]
Hey @phuctm97, 

I just encountered the exact same problem using Chakra UI's modal : the picker wasn't scrollable when inside the modal.

It seems to be related to the fact that these overlays **disable the body scroll while they are mounted** (for accessibility reasons), and for some reason it affects emoji-mart.

In my case, setting `blockScrollOnMount` to false was enough, but I didn't find the equivalent for Radix UI.

**Comment by phuctm97** [comment]
Thank you for the update @benjaminwaterlot, that helped a lot with investigation in Radix UI. I believe Radix UI set body style to block scroll when modal is being shown too!

**Comment by samuelkarani** [comment]
@phuctm97  Were you able to fix the issue?  I have run into it.

**Comment by leoyli** [comment]
@samuelkarani do you have a solution?

**Comment by komagroup** [comment]
I fixed it with `modal={false}` on the `DropdownMenu` with shadCN.

Probably works for popover and their friends

```js
// modal={false} enables the scrolling
<DropdownMenu modal={false}>
  <DropdownMenuTrigger asChild>
    <Button variant="ghost" size="icon">
      <SmileIcon size={18} />
    </Button>
  </DropdownMenuTrigger>
  <DropdownMenuContent align="end">
    <Picker
      searchPosition={"none"}
      theme={theme as Theme}
      data={data}
      onEmojiSelect={(e: any) => onSelect(e.native)}
    />
  </DropdownMenuContent>
</DropdownMenu>
```

**Comment by aiden296** [comment]
<img width="424" alt="image" src="https://github.com/user-attachments/assets/43b0b19a-3743-4a60-8369-da6b575d0e31">

When I placed the emoji picker within a Radix popover (which is placed inside the dialog like in the image above), I was still having this problem. Do you have a solution?

**Comment by maximedeoliveira** [comment]
Hey @aiden296, did you find a solution ? I'm also experiencing this issue when using the emoji picker in a popover (which is in a dialog).

**Comment by aiden296** [comment]
Hi @maximedeoliveira, I solved this issue. Sorry I didn't see your question sooner, but I thought someone coming along would need it.

```
// Fix issue can not scroll on shadow DOM inside Popover content of radix UI
  useEffect(() => {
    const handleWheel = (e: WheelEvent) => {
      if ((e.target as Element).closest("[data-scrollable]")) return;
      e.stopPropagation();
    };

    const handleTouchMove = (e: TouchEvent) => {
      if ((e.target as Element).closest("[data-scrollable]")) return;
      e.stopPropagation();
    };

    document.addEventListener("wheel", handleWheel, true);
    document.addEventListener("touchmove", handleTouchMove, true);

    return () => {
      document.removeEventListener("wheel", handleWheel, true);
      document.removeEventListener("touchmove", handleTouchMove, true);
    };
  }, []);
```
Let put it where you use the emoji picker.

**Comment by Ochirsaikhan** [comment]
If anybody is still having this issue, the problem is that the Picker component is propagating the scroll event to the Radix Popover/Dialog which prevent page scrolling while open. I solved this by wrapping the Picker component inside a div that stops the scroll event propagation:

```tsx
<PopoverContent className="w-auto p-0 " align="start">
  <div
    onWheel={(event) => {
      // Prevent the wheel event from bubbling up to Radix components
      event.stopPropagation();
    }}
  >
    <Picker
      data={data}
      onEmojiSelect={(emoji: { native: string }) =>
        handleUserEmoji(emoji.native)
      }
      theme="light"
      previewPosition="none"
      skinTonePosition="none"
    />
  </div>
</PopoverContent>;
```
